### ISSUE TITLE
Unclear first run info

### ISSUE THREAD

**Issue by dominikmicuta** [zoe-codez/automation-quickstart#1]
When I started the quick guide I immediately got to problem when npm run develop produced:
`
[Tue 10:00:25.345] [hass:entity] (onPostConfig): pre populate MASTER_STATE
[Tue 10:00:25.387] [boilerplate:fetch] (hass:fetch): unexpected api Response
  text: '401: Unauthorized'
[Tue 10:00:25.389] [boilerplate:wiring] (Bootstrap): bootstrap failed
  error: TypeError: states.forEach is not a function
`
There is absolutely no info that first thing that needs to be done is to adjust file: .home_automation
and put there LongLiveToken and adjust url if necessary.

Please add this as step for newcommers.

**Comment by zoe-codez** [comment]
The file should have been removed as part of setup, but it also should have those variables commented out by default to not cause this issue in the first place. You may be experiencing issues with `.type_writer` also. If you are on a supervised setup, the credentials in both files aren't needed, and you can empty them out / delete safely

I'll make those corrections, and add a more descriptive log statement for similar connection & credential errors. Thank you for pointing it out

**Comment by dominikmicuta** [comment]
Actually Im on HAOS and yes, I had issues with type_writer as well but not from point of accessing HA but with one of my device which is missing domain - I had to manually adjust undefined to static domain in code.

Btw do you have a discord or other communication canal?

**Comment by zoe-codez** [comment]
I do now - https://discord.gg/y23D4R3XGq

**Comment by zoe-codez** [comment]
Tweaked default configs to not cause issues, and added a callout to the readme
